---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[ws_users::default]
      - recipe[ws_zsh::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
